apiVersion: v1
kind: Service
metadata:
  name: hitasoft-service
  namespace: hitasoft
spec:
  type: NodePort
  selector:
    app: hitasoft-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30007